### ISSUE TITLE
unsigned integer:  strutils.nim(1091) 

### ISSUE THREAD

**Issue by adrianmihalko** [inv2004/ttop#18]
I am getting error while opening ttop:

```
@ubuntu:~$ sudo ttop
invalid unsigned integer: 
strutils.nim(1091)       parseUInt
```

**Comment by inv2004** [comment]
@adrianmihalko 
Can you please run `ttop-debug` version? It will output stacktrace for the error. Thank you

**Comment by inv2004** [comment]
@adrianmihalko 
Please find that the last version provides more detailed error info even without stacktrace (non -debug)

**Comment by adrianmihalko** [comment]
I can’t reproduce the issue for now, after a restart. I’ll add more info when it appears again. Thank you
