### ISSUE TITLE
Error parsing COMM with spaces parsing

### ISSUE THREAD

**Issue by hugosenari** [inv2004/ttop#2]
I'm so happy that your application fixed my low hardware resources, and now my 4GB RAM machine has a 1TB memory process running. Thank you!

Jokes a side, I think there is something when parsing command with spaces for threads.

Additional info:
Tested with static version 0.3.1 in NixOS Unstable

![shot-2022-12-21_12-41-09](https://user-images.githubusercontent.com/863299/208944412-119e12d5-24ed-4923-acd8-0a4be35c85e5.jpg)

example (htop):
![shot-2022-12-21_12-42-49](https://user-images.githubusercontent.com/863299/208944812-afe5fc35-7450-4e55-88e0-8d29de5bdec2.jpg)

Any additional info I could provide to better debug it?

Other than that, ttop is really cool :heart_eyes:

**Comment by inv2004** [comment]
Thank you for report. I will check it

**Comment by inv2004** [comment]
@hugosenari Can you please send me the processes dump like
```bash
cat /proc/<PID>/stat | hexdump
```

Thank you,

**Comment by hugosenari** [comment]
**Work**:
1146 (**(sd-pam)**) S 1145 1145 1145 0 -1 1077936448 54 0 0 0 0 0 0 0 20 0 1 0 2114 174100480 209 18446744073709551615 1 1 0 0 0 0 0 4096 0 0 0 0 17 0 0 0 0 0 0 0 0 0 0 0 0 0 0

182 (**kworker/3:1H-kblockd**) I 2 0 0 0 -1 69238880 0 0 0 0 0 362 0 0 0 -20 1 0 172 0 0 18446744073709551615 0 0 0 0 0 0 0 2147483647 0 0 0 0 17 3 0 0 0 0 0 0 0 0 0 0 0 0 0

216 (**jbd2/sda2-8**) S 2 0 0 0 -1 2359360 0 0 0 0 0 1232 0 0 20 0 1 0 262 0 0 18446744073709551615 0 0 0 0 0 0 0 2147483647 0 0 0 0 17 0 0 0 0 0 0 0 0 0 0 0 0 0 0

217 (**ext4-rsv-conver**) I 2 0 0 0 -1 69238880 0 0 0 0 0 0 0 0 0 -20 1 0 262 0 0 18446744073709551615 0 0 0 0 0 0 0 2147483647 0 0 0 0 17 2 0 0 0 0 0 0 0 0 0 0 0 0 0

**Fail**

431865 (**RDD Process**) S 430297 430297 430297 0 -1 4194560 385259 0 729295 0 18629 2185 0 0 23 3 3 0 60210948 585064448 6531 18446744073709551615 94764161516320 94764162680672 140731739674000 0 0 0 0 69634 1073745144 0 0 0 17 0 0 0 0 0 0 94764162722848 94764162723304 94764185280512 140731739682173 140731739682471 140731739682471 140731739692970 0

468902 (**Isolated Web Co**) S 430297 430297 430297 0 -1 4194560 345968 0 21937 0 6608 1027 0 0 23 3 22 0 72697463 2713923584 17528 18446744073709551615 94464431477536 94464432641888 140731041055888 0 0 0 0 69634 1082133752 0 0 0 17 3 0 0 0 0 0 94464432684064 94464432684520 94464456769536 140731041064168 140731041064511 140731041064511 140731041075114 0

**Hexdump**
```bash
cat /proc/468902/stat|hexdump -C
00000000  34 36 38 39 30 32 20 28  49 73 6f 6c 61 74 65 64  |468902 (Isolated|
00000010  20 57 65 62 20 43 6f 29  20 53 20 34 33 30 32 39  | Web Co) S 43029|
00000020  37 20 34 33 30 32 39 37  20 34 33 30 32 39 37 20  |7 430297 430297 |
00000030  30 20 2d 31 20 34 31 39  34 35 36 30 20 33 35 30  |0 -1 4194560 350|
00000040  33 39 37 20 30 20 32 31  39 34 30 20 30 20 36 36  |397 0 21940 0 66|
00000050  36 32 20 31 30 34 30 20  30 20 30 20 32 33 20 33  |62 1040 0 0 23 3|
00000060  20 32 32 20 30 20 37 32  36 39 37 34 36 33 20 32  | 22 0 72697463 2|
00000070  37 31 33 39 32 33 35 38  34 20 31 37 36 33 33 20  |713923584 17633 |
00000080  31 38 34 34 36 37 34 34  30 37 33 37 30 39 35 35  |1844674407370955|
00000090  31 36 31 35 20 39 34 34  36 34 34 33 31 34 37 37  |1615 94464431477|
000000a0  35 33 36 20 39 34 34 36  34 34 33 32 36 34 31 38  |536 944644326418|
000000b0  38 38 20 31 34 30 37 33  31 30 34 31 30 35 35 38  |88 1407310410558|
000000c0  38 38 20 30 20 30 20 30  20 30 20 36 39 36 33 34  |88 0 0 0 0 69634|
000000d0  20 31 30 38 32 31 33 33  37 35 32 20 30 20 30 20  | 1082133752 0 0 |
000000e0  30 20 31 37 20 31 20 30  20 30 20 30 20 30 20 30  |0 17 1 0 0 0 0 0|
000000f0  20 39 34 34 36 34 34 33  32 36 38 34 30 36 34 20  | 94464432684064 |
00000100  39 34 34 36 34 34 33 32  36 38 34 35 32 30 20 39  |94464432684520 9|
00000110  34 34 36 34 34 35 36 37  36 39 35 33 36 20 31 34  |4464456769536 14|
00000120  30 37 33 31 30 34 31 30  36 34 31 36 38 20 31 34  |0731041064168 14|
00000130  30 37 33 31 30 34 31 30  36 34 35 31 31 20 31 34  |0731041064511 14|
*
00000150  30 37 33 31 30 34 31 30  37 35 31 31 34 20 30 0a  |0731041075114 0.|
00000160
```

**Comment by inv2004** [comment]
@hugosenari Please try the last v0.3.2

**Comment by hugosenari** [comment]
Worked, thank you
