### ISSUE TITLE
High CPU usage on keypress

### ISSUE THREAD

**Issue by nicck** [inv2004/ttop#21]
Not sure if it's a bug, but ttop is consuming 100% CPU (according to ttop itself) when user repeatedly press up or down arrow key. Users have to do it to scroll the list of processes.

**Comment by inv2004** [comment]
Probably it constantly reload and redraw all stats, let me check

**Comment by inv2004** [comment]
@nicck Please check https://github.com/inv2004/ttop/releases/tag/v0.8.7

Should be fixed here: https://github.com/inv2004/ttop/commit/b16e442b1f305ac816c22bbb460b49c668c8ac6c

**Comment by inv2004** [comment]
@nicck I found some snap mounts on your screenshot and decided to filter-out snap's mount from results in https://github.com/inv2004/ttop/releases/tag/v0.8.8

**Comment by nicck** [comment]
Now CPU usage is only around 10% when I span 'up' key. Nice.
