### ISSUE TITLE
Not recording historical data

### ISSUE THREAD

**Issue by dnordberg** [inv2004/ttop#27]
Installed via the executable on Centos 8.

Ran `ttop --on`.

Got

```
systemctl daemon-reload
systemctl enable --now 'ttop.timer'
```

Ran that. Then running `ttop` again says "No historical stats found".

Sorry if I'm missing something, perhaps I missed a step.

**Comment by inv2004** [comment]
I just released https://github.com/inv2004/ttop/releases/tag/v1.2.5 to avoid confusion while waiting for the first snapshot save

**Comment by inv2004** [comment]
Reopen if actual, plz
