### ISSUE TITLE
[ERROR] Failed to stop ttop.timer: Unit ttop.timer not loaded.

### ISSUE THREAD

**Issue by hamidb80** [inv2004/ttop#29]
I don't know what happened, I just was trying to stop it

```
ttop --off
```
output:
```
systemctl is-active --quiet / 
systemctl --user stop 'ttop.timer' 
Failed to stop ttop.timer: Unit ttop.timer not loaded.

cmd error code: 5
onoff.nim(141)           cmd
```

--------------------

```
nim 1.6.14
ubuntu 20.04.01 LTS
```

**Comment by inv2004** [comment]
You can check timers with
```bash
systemctl list-timers --user
```

and if the `ttop.timer` was not activated - no needs to deactivate it

**Comment by hamidb80** [comment]
> but deactivates it from another user?
I think so,

Thank you so much, I understood my mistake, now it works find
