### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by matkuki** [inv2004/ttop#31]
Hi,

My specs:
- Pop!_OS
- Nim 2.0.2

Cloning the repository and building with `nimble build`, it throws:
```
home/user/Nim/ttop/src/ttop/tui.nim(502, 16) Error: undeclared identifier: 'getKeys'  candidates (edit distance, scope distance); see '--spellSuggest': 
 (1, 6): 'getKey'
       Tip: 12 messages have been suppressed, use --verbose to show them.
nimble.nim(229)          buildFromDir

    Error:  Build failed for the package: ttop
```

**Comment by inv2004** [comment]
@epasveer just pushed small update for the old nim compatibility

git pull and try again plz

**Comment by matkuki** [comment]
@inv2004 
Confirming that the above procedure works, thanks 👍

**Comment by epasveer** [comment]
> @epasveer just pushed small update for the old nim compatibility
> 
> git pull and try again plz

Thanks. I will later today after work.

**Comment by inv2004** [comment]
Reopen if problem still exists

**Comment by epasveer** [comment]
The latest "pull" works well for me.
