### ISSUE TITLE
top line is hard to read for me

### ISSUE THREAD

**Issue by ITwrx** [inv2004/ttop#32]
using adwaita-dark in xfce (f38) the top bar background is a light teal with white text making it hard on the eyes for reading.

![ttop_top_bar](https://github.com/inv2004/ttop/assets/1002762/8835cbe7-22cc-4472-a32f-cc23ea0f19bd)

thanks

**Comment by inv2004** [comment]
Do you build it from source?

I ask because it would be easier to provide and example with different colors to choose one

**Comment by ITwrx** [comment]
no, i just downloaded the binary.  I mainly wanted to report in case it's something you wanted to improve.

**Comment by inv2004** [comment]
@ITwrx Can you please download _debug_ version of https://github.com/inv2004/ttop/releases/tag/v1.4.2 

And run it like `ttop_debug --colors` and show picture of the output. It should show all available palette.

At the moment I expect that the color that you see is number 71, maybe we can find something else which fits you and other terminals

**Comment by ITwrx** [comment]
Did you want me to upload the picture? or just look at it and give you a number that works better for my terminal?

**Comment by ITwrx** [comment]
If you wanted to keep the cyan background, then i would guess color 64, 68, or 69 would provide enough contrast in `gnome terminal` in xorg (what i am currently using and was using when I reported). I also just tested the current default color in `xfce4 terminal` and you can read it, but the contrast is not great. The contrast of the current color was fine in the `Konsole` terminal in xorg session.

**Comment by inv2004** [comment]
I think that it would be perfect if you can upload picture - just to have option to choose from my side and to have better understanding about other colours too

**Comment by ITwrx** [comment]
![ttop_colors1](https://github.com/inv2004/ttop/assets/1002762/34892d02-c10f-496a-9294-a20421917886)
![ttop_colors2](https://github.com/inv2004/ttop/assets/1002762/aee6b1ee-f1a7-485c-a3a2-c52517ee3402)

**Comment by inv2004** [comment]
Is it possible that it is some misconfiguration in the there?

I checked several terminals including the xfce with different schemes and I see that White color is white, but on your picture white is None (default color) only

**Comment by ITwrx** [comment]
Anything is possible, but i just played with the color settings in gnome terminal a little and i'm not seeing anything customized. It's using "use colors from system theme", which is Adwaita-Dark in xfce settings panel.  My primary terminal is gnome-terminal in xfce and xorg session for now. I want to move to hyprland, but the workspace switcher is not per my preference right now. 

If it were me, i would just not use white with cyan background. That is a light/bright background with light text. That's just asking for trouble, imho. I would always use dark background with light text, or dark text with light background. Then it should at least be visible with any sane config or terminal. I've seen this issue (light w light/bright) with different OS/terminals before, probably with Midnight Commander.

**Comment by inv2004** [comment]
https://github.com/inv2004/ttop/releases/v1.4.3

I decided to remove all bg-colors

**Comment by ITwrx** [comment]
looks good to me! Thanks!
