### ISSUE TITLE
FR: option to consolidate processes of same program when sorting by cpu/mem

### ISSUE THREAD

**Issue by ITwrx** [inv2004/ttop#33]
IDK how difficult it would be, but i would find these system monitors(ttop, htop) more useful if when sorting by CPU or MEM usage there were an option (or by default) to consolidate all the processes and show the overall usage of the programs in question; like `ps_mem` does for mem usage.

**Comment by inv2004** [comment]
Do I understand correct:

ps_mem shows:
`13.9 MiB +   3.7 MiB =  17.6 MiB       fish (5)`

ttop with filter "fish"
```
 S   7500 u           10.5 MB   0.1   0.0            0:20:40  /usr/sbin/fish
 S     10 u           10.5 MB   0.1   0.0            0:57:40  -fish
 S   1118 u            8.7 MB   0.1   0.0            0:57:00  /usr/sbin/fish
 S  13293 u            8.3 MB   0.1   0.0            0:10:26  -fish
 S    673 u            7.0 MB   0.1   0.0            0:57:09  /usr/sbin/fish -c sh -c '"$VSCODE_WSL_EXT_LOCATION/s.
 ```

do you mean to group then by ?name? and sum values? I think it is interesting idea - not a lot of reasons to see 100500 threads of the same process.

**Comment by ITwrx** [comment]
> do you mean to group them by ?name? and sum values?

yes. that's what i like about `ps_mem` and i always have to leave `htop` to use `ps_mem` because looking at a bunch of separate forked processes bouncing around is fairly useless when you want to know how much ram a program is using altogether, which i think is a more common use case than some nerd wondering what one particular fork is doing _**right now**_.  :smile: I think it's just legacy status quo that noone except `ps_mem` has bothered to address.

Same thing with CPU usage. I want to know how much a _program_ is using, not try and guess from forks bouncing around. I understand it wouldn't be 100% accurate/real time, but that's still better than chasing the forks. I don't know how your historical data feature works yet, but there may be a "tie in" with this feature there as well. 

I bet ttop would be the only sys mon that had this feature, and it might drive adoption and create exposure for your app and nim.

**Comment by inv2004** [comment]
@ITwrx first try to group processes was added into https://github.com/inv2004/ttop/releases/tag/v1.4.2
You can try it by `g` button. But I have to check it a bit more

**Comment by inv2004** [comment]
https://github.com/inv2004/ttop/releases/v1.4.3

I found that parsing `<PID>/exe` symling like ps_mem do is not very stable and decided to try just first argument from cmdline. And looks like it works a bit better for me

**Comment by ITwrx** [comment]
Yeah, i just tried it too. This is a great feature! closing. Thanks a lot. Will likely be using ttop as my main sys mon now.

**Comment by ITwrx** [comment]
it looks like gajim is shown simply as `/usr/bin/python3`. I'm not seeing anything else that is reported in such a generic way, but that's probably the only python application i have running right now.

**Comment by ITwrx** [comment]
My gajim is in a strange state right now. copr repo, signing keys, etc. let me make sure that's squared away before you spend any time on this. I'll post back.

**Comment by ITwrx** [comment]
well, the copr repo issues are irrelevant as only the omemo stuff is from the copr repo. The gajim package itself is from the official repos. I also confirmed, by closing and reopening gajim, that it is gajim that is shown as `/usr/bin/python3`.

**Comment by inv2004** [comment]
@ITwrx 
I just released v1.4.5 which is mainly about fixing all the group stuff. I found that ps_mem uses root perms to find exe link which is not compatible with ttop (which does not need root).

I added logic to group by first cmdline file (for firefox) if it is possible and use process name if not

**Comment by ITwrx** [comment]
looks good to me! gajim is shown as: `/usr/bin/python3 -sP /usr/bin/gajim`
I'll let you close the issue when you decide to. Thanks!

**Comment by inv2004** [comment]
@ITwrx 
I think it is correct. I groupped by it's process name, but the tui contains cmdline if it is available

**Comment by inv2004** [comment]
Reopen if you find smth I can add to the issue
