### ISSUE TITLE
SIGSEGV when saving the snapshot.

### ISSUE THREAD

**Issue by KnightMurloc** [inv2004/ttop#35]
When calling the command: `ttop -s` i get:
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
```

the steps of reproduction :
1. start docker container with ubuntu 20.04: `docker run -it --rm ubuntu:20.04 bash`
2. install ttop: `apt update`, `apt install curl` and `curl -LO https://github.com/inv2004/ttop/releases/latest/download/ttop`, `chmod +x ttop`
3. run `./ttop -s`

**Comment by inv2004** [comment]
@KnightMurloc 
should be fixed here: https://github.com/inv2004/ttop/releases/tag/v1.5.3

Please let me know if it works

**Comment by KnightMurloc** [comment]
Yes, it's all right now.
