### ISSUE TITLE
Failed to generate random number

### ISSUE THREAD

**Issue by arthur-lbchn** [inv2004/ttop#38]
Hi, 'm trying to run ttop for historical tracking, but getting the error

root@srv2 [~]# ./ttop -s
Failed to generate random number
zippy.nim(33)            compress

The ttop itself opens just fine.

Thank you in advance.

**Comment by inv2004** [comment]
@arthur-lbchn 
Which OS do you use? Because it uses operation system random generator for security reasons

**Comment by inv2004** [comment]
reopen if still actual
