### ISSUE TITLE
/proc/PID/stat parsing bug

### ISSUE THREAD

**Issue by c-blake** [inv2004/ttop#5]
Looks like you fell victim to this:

    https://news.ycombinator.com/item?id=34093845

Workarounds are more complex parsing {i.e. first find the *last* occurrence of ')' } or using /proc/PID/stat***us*** which escapes special characters in the command name (after Name:HARDTAB, that is).

**Comment by inv2004** [comment]
I expect it is fixed here: https://github.com/inv2004/ttop/issues/2

But let me recheck. Do you have specific `stat` which fails?

**Comment by c-blake** [comment]
The problem (as explained in the URI I gave) is that a command name in Unix can have any bytes in it besides `{'/', '\0'}` BUT that `scanf(line, "$i ($+) $w $i ...` construct [you use here](https://github.com/inv2004/ttop/blob/main/src/ttop/procfs.nim#L177) cannot parse that in its full generality.

If you need to reproduce the problem in order to believe there is a problem, have `ttop` be running in one window and in another do something like:
```sh
$ ln -s /bin/sleep '/tmp/this
has
three lines'
$ /t/this$'\n'has$'\n'three\ lines 5
```
where existing for 5 seconds should ensure the PID gets sampled/read/parsed by your tool.  That `$\n` syntax I use works in Bash or Zsh.

You just need to "pre-bracket" the command name that could have weird special characters in it such as the `cmd0`, `cmd1` in https://github.com/c-blake/procs/blob/master/procs.nim#L223 or like https://github.com/ibaoger/procps/blob/master/proc/readproc.c#L591 or you can use the `/proc/PID/status` file instead of `/proc/PID/stat` file to get the data.  `/proc/PID/status` has a more robust syntax to parse: `Name:TAB<sanitizedCommandName>`.

**Comment by inv2004** [comment]
@c-blake I slowly understood that that _anything_ can contains not only `\n` or `)` but `) ` which brakes the scanf patter which looked ok.

Should be fixed here: https://github.com/inv2004/ttop/commit/50160f978f10bac0546ff05cff78f90eab2d267f

Thank you for pointing to the problem

**Comment by c-blake** [comment]
Your fix looks correct to me.  Easy to test by symlinking `sleep` to commands with `')'` or newline or spaces and so on.  I would say if it tests out ok for you then you can close this issue.

And you are welcome.  As per my opening ycombinator link, this is a "trap" that catches many devs - it *seems* easier to parse than it actually *is*.  For me, just having `firefox` running seemed to cause your `ttop` to fail on my system (but I was well aware of the trap before that..since at least 1994, actually).

Incidentally, the same idea can also be used to workaround CSV with no quotes/escapes where *at most 1* field can contain commas (or whatever the delimiter is).  That might sound rare, but "company name" is often that "more free-form" field in financial settings where sometimes file formats pre-date "Excel". :-)  Everything *except* the company name might be much more well defined/never contain a delimiter.  So, I have actually run into this situation in real life.  There you need to count backwards the right number of delimiters which is slightly more involved.  (I believe when I ran into it, the delimiter was `'|'` for some FactSet data.)

**Comment by inv2004** [comment]
@c-blake Please find that newline or `)` did not caused any problems with initial scanf pattern, but `) ` did

Probably some optimization can be made by finding from left to right for both brackets because I saw the field has limitation to ?16? bytes

**Comment by c-blake** [comment]
Well, in https://github.com/torvalds/linux/blob/master/fs/proc/array.c#L98 (proc_task_name) they act like it could be as long as 64 bytes (or maybe 63 counting the terminating NUL), but other places it is indeed declared to be `comm[16]`.  I agree that it's best to be safer to weird changes on this one.

I doubt the `rfind` is very slow in practice, anyway.  It should be in the CPU L1 cache by the time the `rfind`/`strrchr` happens.  In context, it is much slower to make a single system call even to a magic FS with no IO device backing it.  And open/read/close is already 3 such calls per PID.  /proc/PID/stat is a small file.  The ASCII to binary decimal conversion you do for every field also probably costs a lot more than the reverse search.  It might be difficult to even measure any improvement, to be honest.
