### ISSUE TITLE
"looks like" miss

### ISSUE THREAD

**Issue by white-dragon** [inv2004/ttop#8]
```
% ./ttop --on  
systemctl check 'ttop.timer' 
/bin/sh: systemctl: command not found

cmd error: Looks like ttop.timer is already running system-wide
onoff.nim(70)            cmd

```

**Comment by inv2004** [comment]
@white-dragon could you please let me know OS you use? 
You can enable it via Cron like: ‘*/10 * * * * ttop -s‘

**Comment by inv2004** [comment]
I going to implement cron support via `--on` parameter

**Comment by white-dragon** [comment]
альт линукс у меня, причем на sysvinit, тобишь у меня systemctl просто нет вообще
я к тому, что оно говорит что мол мохоже что он системвайд запущен - нифига не похоже :)
очень странное предположение :)

**Comment by inv2004** [comment]
Да, с фразой конечно мимо - поправлю. Причем я начал делать на одной машине - там был крон, а потом, с удивлением, обнаружил что он уже опциональный во многих системах и переделал.

**Comment by inv2004** [comment]
Crontab support added in v0.4.8: https://github.com/inv2004/ttop/releases/tag/v0.4.8

Please let me know if something does not work there
